version: '2.1'
services: 
  discovery:
    image: jbcnconf/discovery
    restart: on-failure:10 
    container_name: discovery
    expose:
      - 8761
    ports:
      - 8761:8761   
      
  gateway:  
    image: jbcnconf/api-gateway
    restart: on-failure:10
    container_name: gateway
    depends_on:  
      - discovery
    expose:
     - 90
    ports:
     - 90:90
         
  dashboard:
    image: jbcnconf/admin-dashboard
    container_name: admin-dashboard
    restart: on-failure:10
    depends_on:  
      - discovery
    ports:
      - 8090:8080
    expose:
      - 8080
       
networks:
  default:
    external:
      name: msworkshop_jbcnconf